Update key repository
Xobb/ansible-percona pull request #3
Opened 2016-10-22 14:29 UTC by fradee

Перестала працювати роляка по причині таких вот змін:

https://www.percona.com/blog/2016/10/13/new-signing-key-for-percona-debian-and-ubuntu-packages/

Перевірено!

2016-10-22 16:41 UTC, paulchubatyy commented
Саша, не годен мерджити, конфліктує. Відребейсись.

2016-10-22 20:37 UTC, paulchubatyy requested changes
Оце варто пофіксити разом з конфліктом.

2016-10-22 20:37 UTC, paulchubatyy commented on defaults/main.yml
> +sqldebug: true # for enable in custom setings file slow log queries
це погана ідея мати в дефолтній конфігурації. дефолтна конфігурація має бути націлена на production values.

2016-10-22 20:37 UTC, paulchubatyy commented on defaults/main.yml
> +percona_repo_key_server: "keyserver.ubuntu.com"
варто мати ще одненьку пустеньку стрічку в кінці файлу.

2016-10-24 18:04 UTC, closed without merging

2016-10-24 18:14 UTC, fradee commented on defaults/main.yml
> +sqldebug: true # for enable in custom setings file slow log queries
Якщо можна в Хіпчаті детальніше, будь ласка.